### ISSUE TITLE
Atualizar app.json

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-trustvox#1]
@talissonf eu preciso instalar este app e vi que o admin settings está vazio, possivelmente tem mais coisas incorretas ou desatualizadas no [app.json](https://github.com/ecomclub/app-trustvox/blob/master/assets/app.json), pode priorizar isto por favor?

**Comment by leomp12** [comment]
Também notei que no `auth_scope` você pede todos os métodos pro endpoint `procedures`, você só precisa criar procedures, não? Não seria só _POST_?

**Comment by talissonf** [comment]
@leomp12 esse app realmente nao tem nenhum admin_settings e o auth_scope seria só post mesmo.

**Comment by leomp12** [comment]
Na verdade precisamos permitir que o lojista configure as credenciais (id, token) via admin settings para migrar contas já existentes.

**Comment by talissonf** [comment]
Pronto
