### ISSUE TITLE
Retirar a autenticação da trustvox por link

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-trustvox#3]
Em conversa com a trustvox hoje, a autenticação tem que ser apenas por apikey e storeid. A segunda autenticação de criar loja vai ser descontinuada. Eles orientaram o comercial deles ao entrar em contato, eles irão fornecer a apikey e store id. A url você precisa para alguma coisa? Se não precisar, pode tirar também

**Comment by talissonf** [comment]
Não, a url é pra justamente procurar a autenticação caso o lojista não informe storeId e apiKey, mas nunca funciona corretamente porque os lojistas sempre informam urls inválidas 😫 .
Vou remover tudo.

**Comment by matheusgnreis** [comment]
Sim e eles vão desativar esse módulo, então não faz sentido ter. Só hoje que um lojista fez certo. Como o reclame aqui comprou a trustvox, eles mudaram tudo lá dentro, então, essa autenticação ai mesmo eles não têm controle. Então deixa, só store id e token ne

**Comment by talissonf** [comment]
https://github.com/ecomplus/app-trustvox/commit/7684775ed9cb885af4866d44c6d96c0ce5090026
